Added code in NFT backend to check for iptable version
kubernetes-sigs/kpng pull request #28
Opened 2021-05-24 13:51 UTC by hanamantagoudvk

This is fix for issue

2021-05-24 15:07 UTC, mcluseau requested changes

2021-05-24 15:07 UTC, mcluseau commented on backends/nft/nft.go
> +			log.Printf("cmd (%v) throws error: %v", cmd, err)
use klog; log this only `if errors.Unwrap(err) != exec.ErrNotFound`

2021-05-25 16:40 UTC, hanamantagoudvk commented on backends/nft/nft.go
> +			log.Fatal("legacy iptable found")
But @jayunit100 wanted to fail the container itself , so i added Fatal. If we just want to log the warning, i can modify it to warn.

2021-05-26 12:45 UTC, mcluseau commented on backends/nft/nft.go
> +			log.Fatal("legacy iptable found")
in a follow up discussion we got aligned, we don't want to force fail people who think they're right, as they may be right ;)

2021-05-27 12:22 UTC, merged