[WIP] Add Metrics + Metrics server
kubernetes-sigs/kpng pull request #370
Opened 2022-10-13 15:56 UTC by astoycos

Starts to fix https://github.com/kubernetes-sigs/kpng/issues/351

Working Prototype 

TODO:
Add Documentation 
Cleanup Code

2022-10-16 11:48 UTC, jayunit100 commented on hack/test_e2e.sh
> +while getopts "i:b:B:cdD:eE:n:ps:t" flag
```suggestion
while getopts "i:b:B:cdD:eE:n:ps:t:m" flag
```

2022-10-17 12:58 UTC, astoycos commented on cmd/go.mod
> +	sigs.k8s.io/kpng/api v0.0.0-20221014160047-e8543ceff80f
We shouldn't need to add these

2022-10-17 13:08 UTC, astoycos commented on cmd/go.mod
> +	github.com/cilium/ebpf v0.8.1 // indirect
Yeah something is going on here we shouldn't have a dependency on cilium/ebpf here

2022-10-17 19:07 UTC, astoycos commented on hack/test_e2e.sh
> +while getopts "i:b:B:cdD:eE:n:ps:t" flag
Done

2022-10-17 19:09 UTC, astoycos commented
I think I got to most of your recommendations here @jayunit100

2022-10-18 18:38 UTC, aryan9600 requested changes

2022-10-18 18:38 UTC, aryan9600 commented on server/jobs/api2local/api2local.go
> +	NodeName      string
```suggestion
	NodeName string
```

2022-10-18 18:38 UTC, aryan9600 commented on server/jobs/kube2store/kube2store.go
> +	UseSlices     bool
```suggestion
	UseSlices bool
```

2022-10-18 18:38 UTC, aryan9600 commented on server/pkg/metrics/metrics.go
> +var Kpng_k8s_api_events = prometheus.NewCounter(prometheus.CounterOpts{
```suggestion
var KpngK8SApiEvents = prometheus.NewCounter(prometheus.CounterOpts{
```

2022-10-18 18:38 UTC, aryan9600 commented on server/pkg/metrics/metrics.go
> +var Kpng_node_local_events = prometheus.NewCounter(prometheus.CounterOpts{
```suggestion
var KpngNodeLocalEvents = prometheus.NewCounter(prometheus.CounterOpts{
```

2022-10-18 18:38 UTC, aryan9600 commented on server/jobs/kube2store/kube2store.go
> +	UseSlices     bool
Also, this field doesn't seem to be used anywhere else in this PR

2022-10-18 18:38 UTC, aryan9600 commented on cmd/kpng/main.go
> +	exportMetrics = flag.String("exportMetrics", "", "start metrics server on the specified IP:PORT")
```suggestion
	metricsServer = flag.String("metrics-server", "", "start metrics server on the specified IP:PORT")
```

2022-10-18 18:58 UTC, aryan9600 commented on server/pkg/metrics/metrics.go
> +})
```suggestion
var KpngNodeLocalEvents = prometheus.NewCounterVec(prometheus.CounterOpts{
	Name: "kpng_node_local_events_total",
	Help: "The total number of received events from the Kubernetes API for a given node",
}, []strings{"node_name"})
```

2022-10-18 18:58 UTC, aryan9600 commented on server/pkg/server/watchstate/watchstate.go
> +	metrics.Kpng_node_local_events.Inc()
This should increment the counter per label, i.e. per node name. But I don't think we have access to the node name here, maybe we need to move this higher up?

2022-10-20 20:29 UTC, aryan9600 commented on server/pkg/server/watchstate/watchstate.go
> +	metrics.Kpng_node_local_events.Inc()
okay that works for now ig :)

2022-10-21 14:13 UTC, jayunit100 commented
can we merge and iterate on this @aryan9600 @astoycos ?

2022-10-21 14:14 UTC, jayunit100 commented
/lgtm
/approve

lets get this in then we can build more fine grained metrics into it

2022-10-21 14:15 UTC, merged