Include lb and session affinity related parameters to kpng controller
kubernetes-sigs/kpng pull request #64
Opened 2021-09-03 14:13 UTC by VivekThrivikraman-est

2021-09-03 14:54 UTC, mcluseau requested changes

2021-09-03 14:54 UTC, mcluseau commented on pkg/api/localnetv1/services.proto
> +    string SessionAffinity = 10;
remove from here and move to a `SessionAffinity` message...

2021-09-03 14:54 UTC, mcluseau commented on pkg/api/localnetv1/services.proto
> +    SessionAffinityConfig SessionAffinityConfig = 11;
... rename to SessionAffinity...

2021-09-03 14:54 UTC, mcluseau commented on pkg/api/localnetv1/services.proto
> +message SessionAffinityConfig {
rename to SessionAffinity and add `string Kind = 1` that will receive the k8s `SessionAffinity` value

2021-09-03 15:51 UTC, qabpea commented
Session affinity is potentially tricky. There are situations where it does not scale very well, at L4 this typically occurs when there is L4 non transparent proxy or NAT in the way. I can see why you would do this with external IPs, but on the inside  of the cluster there is a potential problem when SNATing a node. The affinity must be set before the SNAT occur, if not then all sessions from one node will be directed towards one POD. This is currently not a problem, but it can/will become a problem if the order of LB and SNAT is not done in the correct order (or even better, never use SNAT for cluster internal traffic)

2021-11-07 12:32 UTC, jayunit100 commented
fixes #93 #64

2021-11-07 15:22 UTC, mcluseau commented
plz test with latest master

2021-11-19 17:30 UTC, jayunit100 commented
all done now by mikael

2021-11-19 17:30 UTC, jayunit100 commented
/close

2021-11-19 17:30 UTC, closed without merging